language: android
android:
  components:
    - tools
    - build-tools-29.0.1
    - android-29
    - platform-tools
  licenses:
    - '.+'

sudo: required

jdk:
  - oraclejdk8

install: true

  yes | sudo sdkmanager --licenses

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease --stacktrace


