language: android
dist: trusty
android:
  components:
    - build-tools-29.0.2
    - android-29
    - add-on
    - extra
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
